version: "3"
services:
  db:
    image: postgres:16
    ports:
      - "5473:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger
      POSTGRES_DB: ledger
#    volumes:
#      - ./src/application/database/schema.sql:/docker-entrypoint-initdb.d/init.sql

#
#volumes:
#  ledger_volume:
#    driver: local
