import { DB_ID } from '@/types.js';
import { v4 as uuid } from 'uuid';

export type DatabaseIdGenerator = {
  generateId: () => DB_ID | null;
};

export class UuidDatabaseIdGenerator implements DatabaseIdGenerator {
  public generateId() {
    return uuid();
  }
}

export class AutogeneratedDatabaseIdGenerator implements DatabaseIdGenerator {
  public generateId() {
    return null;
  }
}
